{{- if and (.Values.ingress.enable) (.Values.service.enable) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if and .Values.ingress.wwwRedirect (eq .Values.ingress.ingressClassName "nginx") }}
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
  {{- end }}
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
    {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: {{ .Values.deployment.container.containerPort | required "A container port is required on the container." }}
        {{- with .Values.ingress.addtionalPaths }}
        {{ toYaml . | nindent 6}}
        {{- end }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    {{- if and .Values.ingress.wwwRedirect (eq .Values.ingress.ingressClassName "nginx") }}
    - www.{{ .Values.ingress.host }}
    {{- end }}
    secretName: {{ .Values.ingress.host | replace "." "-" }}-cert
{{- end }}
