{{- if .Values.ingress.enable }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
    {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.ingress.host }}
    paths:
    - path: /
      pathType: Prefix
      backend:
        service:
          name: {{ .Release.Name }}
          port:
            number: {{ .Values.deployment.container.containerPort | required "A container port is required in the deployment" }}
    {{- with .Values.ingress.addtionalPaths }}
    {{ . | toYaml | nindent 4}}
    {{- end }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.host | replace "." "-" }}-cert
{{- end }}
